# Prometheus Configuration for Skippy Trading Platform
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  # Skippy Trading Platform Metrics
  - job_name: 'skippy-trading-platform'
    scrape_interval: 10s
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['skippy-app:5000']
    scrape_timeout: 8s

  # Self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter (if available)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # PostgreSQL Exporter (if available)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093